# Generated by Django 6.0 on 2026-02-16 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ORDER_PAYMENT", "Order Payment"),
                            ("CANCELLATION_REFUND", "Cancellation Refund"),
                            ("RETURN_REFUND", "Return Refund"),
                            ("WALLET_CREDIT", "Wallet Credit"),
                            ("WALLET_DEBIT", "Wallet Debit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("WALLET", "Wallet"),
                            ("RAZORPAY", "Razorpay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "gateway_signature",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="payments_tr_user_id_d7ba42_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="payments_tr_content_dc666b_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "status"],
                        name="payments_tr_transac_a6e8b9_idx",
                    ),
                ],
            },
        ),
    ]
