# Generated by Django 6.0 on 2026-02-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ORDER_PAYMENT", "Order Payment"),
                    ("CANCELLATION_REFUND", "Cancellation Refund"),
                    ("RETURN_REFUND", "Return Refund"),
                    ("WALLET_TOPUP", "Wallet Topup"),
                ],
                max_length=30,
            ),
        ),
    ]
