# Generated by Django 6.0 on 2026-02-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_transaction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ORDER_PAYMENT", "Order Payment"),
                    ("CANCELLATION_REFUND", "Cancellation Refund"),
                    ("RETURN_REFUND", "Return Refund"),
                    ("WALLET_TOPUP", "Wallet Topup"),
                    ("REFERRAL_REWARD", "Referral Reward"),
                ],
                max_length=30,
            ),
        ),
    ]
