# Generated by Django 6.0 on 2026-03-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                db_index=True, editable=False, max_length=16, unique=True
            ),
        ),
    ]
