# Generated by Django 6.0 on 2026-02-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="label",
            field=models.CharField(
                choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                default="CREDIT",
                max_length=10,
            ),
        ),
    ]
