# Generated by Django 6.0 on 2026-02-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("wallet", "0002_wallettransaction_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transaction",
                to="payments.transaction",
            ),
        ),
    ]
