# Generated by Django 6.0 on 2026-02-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usages",
                to="coupons.coupon",
            ),
        ),
    ]
