# Generated by Django 6.0 on 2026-01-23 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_type",
        ),
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("work", "Work"), ("other", "Other")],
                default="home",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_full_name",
                        message="Please enter a valid full name. Only letters, hyphens, apostrophes, and spaces are allowed.",
                        regex="^[A-Za-zÀ-ÿ]+([-'\\s][A-Za-zÀ-ÿ]+)*$",
                    ),
                    django.core.validators.MinValueValidator(
                        3, message="Name must contain at least 3 letters"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                max_length=6, validators=[django.core.validators.MinLengthValidator(6)]
            ),
        ),
    ]
