# Generated by Django 6.0 on 2026-01-23 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_remove_address_address_type_address_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_full_name",
                        message="Name must start with a letter and can only contain letters, hyphens, apostrophes, and spaces.",
                        regex="^[A-Za-zÀ-ÿ]+([-'\\s][A-Za-zÀ-ÿ]+)*$",
                    ),
                    django.core.validators.MinLengthValidator(
                        3, message="Name must contain at least 3 charators"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[("Home", "Home"), ("Work", "Work"), ("Other", "Other")],
                default="home",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.PositiveIntegerField(
                max_length=6, validators=[django.core.validators.MinValueValidator(6)]
            ),
        ),
    ]
