# Generated by Django 6.0 on 2026-01-23 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0003_alter_address_address_line_2_alter_address_full_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, message="Postal code must be exactly 6 digits"
                    ),
                    django.core.validators.RegexValidator(
                        code="Invalid_code",
                        message="Postal code must be exactly 6 digits",
                        regex="^\\d{6}$",
                    ),
                ],
            ),
        ),
    ]
