# Generated by Django 6.0 on 2026-01-23 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_alter_address_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_full_name",
                        message="Name must start with a letter and can only contain letters, hyphens, apostrophes, and spaces.",
                        regex="^[A-Za-zÀ-ÿ]+([-'\\s][A-Za-zÀ-ÿ]+)*$",
                    ),
                    django.core.validators.MinLengthValidator(
                        3, message="Name must contain at least 3 letters"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalid_code",
                        message="Postal code must be exactly 6 digits",
                        regex="^\\d{6}$",
                    )
                ],
            ),
        ),
    ]
