# Generated by Django 6.0 on 2026-02-08 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_alter_address_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Address line 1 is too short."
                    ),
                    django.core.validators.RegexValidator(
                        message="Address contains unsupported characters.",
                        regex="^[a-zA-Z0-9\\s\\.,#\\-]+$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Address contains unsupported characters.",
                        regex="^[a-zA-Z0-9\\s\\.,#\\-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="This field should only contain letters, spaces, and hyphens.",
                        regex="^[a-zA-Z\\s\\-]+$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="India", max_length=5),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="This field should only contain letters, spaces, and hyphens.",
                        regex="^[a-zA-Z\\s\\-]+$",
                    ),
                ],
            ),
        ),
    ]
