# Generated by Django 6.0 on 2026-02-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0007_alter_address_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
