# Generated by Django 6.0 on 2025-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_created_at_passwordreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User Profile Pic",
                null=True,
                upload_to="user_avatar",
            ),
        ),
    ]
