# Generated by Django 6.0 on 2026-02-07 19:41

import django.core.validators
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User Profile Pic",
                null=True,
                upload_to="user_avatar",
                validators=[
                    core.validators.image_size_validator,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_alphabet",
                        message="Only letters are allowed.",
                        regex="^[A-Za-z]+(?:[A-Za-z]+)*$",
                    ),
                    django.core.validators.MinLengthValidator(
                        3, message="Name must contain at least 3 letters"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_alphabet",
                        message="Only letters are allowed.",
                        regex="^[A-Za-z]+(?:[A-Za-z]+)*$",
                    ),
                    django.core.validators.MinLengthValidator(
                        3, message="Name must contain at least 3 letters"
                    ),
                ],
            ),
        ),
    ]
