# Generated by Django 6.0 on 2026-02-08 12:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_customuser_avatar_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User Profile Pic",
                null=True,
                upload_to="user_avatar",
                validators=[
                    core.validators.image_size_validator,
                    core.validators.image_file_extension_validator,
                ],
            ),
        ),
    ]
