# Generated by Django 6.0 on 2026-02-25 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("reason", models.CharField(default="EMAIL_CHANGED", max_length=30)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_user",
                    models.ForeignKey(
                        help_text="User who originally owned this email",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklisted_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-blacklisted_at"],
            },
        ),
    ]
