# Generated by Django 6.0 on 2026-02-23 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="discount_type",
            field=models.CharField(
                choices=[("PERCENTAGE", "Percentage")],
                default="PERCENTAGE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Percentage value (e.g., 10 for 10%)",
                max_digits=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
