# Generated by Django 6.0 on 2026-02-23 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_alter_offer_discount_type_alter_offer_discount_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="offer",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
