# Generated by Django 6.0 on 2026-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_address_is_active_alter_address_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                default="Home",
                help_text="Address type: Home, Work, or custom label",
                max_length=50,
            ),
        ),
    ]
