# Generated by Django 6.0 on 2026-04-08 08:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0016_alter_inventorylog_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Rating must be at least 1."
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "Rating cannot exceed 5."
                            ),
                        ]
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short summary of your review.", max_length=120
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Share your experience with this timepiece.",
                        max_length=1000,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft-delete / moderation flag."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "product"),
                        name="unique_review_per_user_product",
                    )
                ],
            },
        ),
    ]
