# Generated by Django 6.0 on 2025-12-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
