# Generated by Django 6.0 on 2025-12-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_productvariant_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_drafted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_drafted",
            field=models.BooleanField(default=True),
        ),
    ]
