# Generated by Django 6.0 on 2025-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_drafted_productvariant_is_drafted"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when product was soft deleted",
                null=True,
            ),
        ),
    ]
