# Generated by Django 6.0 on 2025-12-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productvariant_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="Brand Logo", null=True, upload_to="brands-logo"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Product thumbnail image",
                null=True,
                upload_to="product-thumbs/",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ProductVariant Image",
                null=True,
                upload_to="products-image/",
                verbose_name="product_image",
            ),
        ),
    ]
