# Generated by Django 6.0 on 2026-01-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_brand_logo_alter_product_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Discount percentage (0–100)",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
