# Generated by Django 6.0 on 2026-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_productvariant_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
