# Generated by Django 6.0 on 2026-02-04 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_productvariant_price"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change",
                    models.IntegerField(
                        help_text="Positive for stock in, negative for stock out"
                    ),
                ),
                ("stock_before", models.PositiveIntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("RETURNED", "Returned"),
                            ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                            ("SYSTEM_CORRECTION", "System Correction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_variant", "created_at"],
                        name="catalog_inv_product_9f8d3c_idx",
                    ),
                    models.Index(
                        fields=["reason"], name="catalog_inv_reason_f4aad0_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="catalog_inv_content_39eee4_idx",
                    ),
                ],
            },
        ),
    ]
