# Generated by Django 6.0 on 2026-02-07 19:41

import django.core.validators
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_inventorylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, "Please provide a more detailed description (min 20 chars)."
                    ),
                    django.core.validators.MaxLengthValidator(
                        3000, "Description cannot exceed 3000 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Brand Logo",
                null=True,
                upload_to="brands_logo",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif"]
                    ),
                    core.validators.image_size_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(default="temp-slug", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brand",
            name="tagline",
            field=models.TextField(
                blank=True,
                help_text="A brief slogan for the brand (e.g., 'Just Do It').",
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Tagline is a bit too short."
                    ),
                    django.core.validators.MaxLengthValidator(
                        150, "Keep the tagline under 150 characters for better display."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="temp-slug", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, "Please provide a more detailed description (min 20 chars)."
                    ),
                    django.core.validators.MaxLengthValidator(
                        3000, "Description cannot exceed 3000 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Product thumbnail image",
                null=True,
                upload_to="product_thumbs/",
                validators=[
                    core.validators.image_size_validator,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ProductVariant Image",
                null=True,
                upload_to="products_image/",
                validators=[
                    core.validators.image_size_validator,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif"]
                    ),
                ],
                verbose_name="product_image",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="case_material",
            field=models.CharField(
                blank=True,
                help_text="e.g., Genuine Leather, Stainless Steel",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="case_size_mm",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Enter size in mm (e.g., 40)",
                validators=[
                    django.core.validators.MinValueValidator(
                        15, "Smallest watch case size is typically 15mm."
                    ),
                    django.core.validators.MaxValueValidator(
                        65, "Largest watch case size is typically 65mm."
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="dial_color",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                db_index=True,
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9-]*$",
                        "SKU must be uppercase letters, numbers, and hyphens.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="strap_color",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="strap_material",
            field=models.CharField(
                blank=True,
                help_text="e.g., Genuine Leather, Stainless Steel",
                max_length=100,
            ),
        ),
    ]
