# Generated by Django 6.0 on 2026-02-08 12:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_brand_description_alter_brand_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Brand Logo",
                null=True,
                upload_to="brands_logo",
                validators=[
                    core.validators.image_file_extension_validator,
                    core.validators.image_size_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Product thumbnail image",
                null=True,
                upload_to="product_thumbs/",
                validators=[
                    core.validators.image_size_validator,
                    core.validators.image_file_extension_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ProductVariant Image",
                null=True,
                upload_to="products_image/",
                validators=[
                    core.validators.image_size_validator,
                    core.validators.image_file_extension_validator,
                ],
                verbose_name="product_image",
            ),
        ),
    ]
