# Generated by Django 6.0 on 2026-02-15 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_brand_logo_alter_product_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Discount percentage (0–100)",
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
