# Generated by Django 6.0 on 2026-02-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_productvariant_discount_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="discount_percentage",
            new_name="discount_rate",
        ),
    ]
