# Generated by Django 6.0 on 2026-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_rename_discount_percentage_productvariant_discount_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("RETURNED", "Returned"),
                    ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                    ("SYSTEM_CORRECTION", "System Correction"),
                ],
                max_length=30,
            ),
        ),
    ]
