# Generated by Django 6.0 on 2026-02-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total",
            new_name="grant_total",
        ),
    ]
