# Generated by Django 6.0 on 2026-02-12 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_total_order_grant_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="grant_total",
            new_name="grand_total",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "order_number")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "order_number"], name="orders_orde_user_id_39a828_idx"
            ),
        ),
    ]
