# Generated by Django 6.0 on 2026-02-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_grant_total_order_grand_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("CHANGED_MIND", "Changed my mind"),
                            ("WRONG_ITEM_ORDERED", "Ordered wrong item"),
                            ("FOUND_BETTER_PRICE", "Found better price"),
                            ("DELIVERY_DELAY", "Delivery delay"),
                            ("DAMAGED_ITEM", "Item damaged"),
                            ("DEFECTIVE_ITEM", "Item defective"),
                            ("WRONG_ITEM_RECEIVED", "Wrong item received"),
                            ("SIZE_FIT_ISSUE", "Size/Fit issue"),
                            ("QUALITY_NOT_AS_EXPECTED", "Quality not as expected"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="order_return/"),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_user_id_39a828_idx",
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                db_index=True, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="returns",
                to="orders.orderitem",
            ),
        ),
    ]
