# Generated by Django 6.0 on 2026-02-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_return_photo_returnimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("WALLET", "Wallet"),
                    ("RAZORPAY", "Razorpay"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
    ]
