# Generated by Django 6.0 on 2026-02-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_order_payment_method_alter_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="return",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_request",
                to="orders.orderitem",
            ),
        ),
    ]
