# Generated by Django 6.0 on 2026-02-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_return_order_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
    ]
