# Generated by Django 6.0 on 2026-02-24 04:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="MRP / list price at the time the order was placed (before any offer discount)",
                max_digits=10,
            ),
        ),
    ]
