# Generated by Django 6.0 on 2026-03-04 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_coupon_order_coupon_discount"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="statustimeline",
            name="orders_stat_content_225851_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Pending Review"),
                    ("CONFIRMED", "Order Confirmed"),
                    ("SHIPPED", "Dispatched"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Payment Failed"),
                ],
                db_index=True,
                default="PLACED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status_updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PACKING", "Packing"),
                    ("READY", "Ready to Dispatch"),
                    ("SHIPPED", "Shipped"),
                    ("IN_TRANSIT", "In Transit"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Delivery Failed"),
                    ("RTS", "Returned to Sender"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURNED", "Returned"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status_updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StatusTimeline",
        ),
    ]
