# Generated by Django 6.0 on 2026-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0014_remove_statustimeline_orders_stat_content_225851_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Cart data saved at order time, used to create items after Razorpay payment",
                null=True,
            ),
        ),
    ]
