# Generated by Django 6.0 on 2026-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_orderitem_created_at_alter_order_status_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Pending Review"),
                    ("CONFIRMED", "Order Confirmed"),
                    ("SHIPPED", "Dispatched"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Payment Failed"),
                    ("EXPIRED", "Expired"),
                    ("STOCK_UNAVAILABLE", "Stock Unavailable"),
                ],
                db_index=True,
                default="PLACED",
                max_length=20,
            ),
        ),
    ]
