# Generated by Django 6.0 on 2026-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_revoke",
            field=models.BooleanField(default=False),
        ),
    ]
