# Generated by Django 6.0 on 2026-04-08 13:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_coupon_revoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative grand_total deducted via cancellations/returns', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_coupon_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative coupon discount lost via cancellations/returns', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative offer discount lost via cancellations/returns', max_digits=10),
        ),
    ]
