# Generated by Django 6.0 on 2026-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_refunded_amount_order_refunded_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, default='', help_text='Razorpay order ID — set at order creation, cleared after payment', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Awaiting Payment'), ('PLACED', 'Pending Review'), ('CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Dispatched'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Expired'), ('STOCK_UNAVAILABLE', 'Stock Unavailable')], db_index=True, default='PLACED', max_length=20),
        ),
    ]
